# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b048ed738201572282705c04e8923ac0f3392705274dbc98d2a52eb4f5d06f9dc18861c733ad9c454d8c488e2826102803d3f34c33fbf2869c95e801bd7fab7

test:
  secret_key_base: 75abc3f8038c0a254a2592307e12647ed9503eee4c80e34efcb350d231e505d98b46ae83e4c22815da22d345aff07185ff0a1054209b1da476589c139f2fbf10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
